{...}:
{
  imports = [
    ./nixos/cli/starship
    ./nixos/cli/zsh
    ./nixos/cli/nvim
    ./nixos/cli/zoxide
    ./nixos/cli/git
    ./nixos/cli/misc
    ./nixos/cli/yazi
    ./nixos/cli/tmux
    ./nixos/apps/alacritty
    ./nixos/apps/1password
    ./nixos/apps/obsidian
    ./nixos/apps/discord
    ./nixos/apps/firefox
    ./nixos/desktop/hyprland
    ./nixos/desktop/waybar
    ./nixos/desktop/swaync
    ./nixos/desktop/gtk
    ./nixos/desktop/swaylock
    ./nixos/desktop/swayidle
    ./nixos/desktop/swaybg
    ./nixos/desktop/hyprshot
  ];
}
