{...}:
{
  imports = [
    ./nixos/cli/starship
    ./nixos/cli/zsh
    ./nixos/cli/nvim
    ./nixos/cli/zoxide
    ./nixos/cli/git
    ./nixos/cli/misc
    ./nixos/cli/yazi
    ./nixos/cli/tmux
    ./nixos/cli/ssh
    ./nixos/apps/alacritty
    ./nixos/apps/obsidian
    ./nixos/apps/discord
    ./nixos/apps/firefox
    ./nixos/apps/prismlauncher
    ./nixos/desktop/hyprland
    ./nixos/desktop/waybar
    ./nixos/desktop/swaync
    ./nixos/desktop/gtk
    ./nixos/desktop/hyprlock
    ./nixos/desktop/swayidle
    ./nixos/desktop/swaybg
    ./nixos/desktop/hyprshot
    ./nixos/desktop/blueberry
  ];
}
